#!/usr/bin/env python3
"""
embed_pubkey.py — convert keys/signing_public.pem into main/signing_pubkey.h.

The output file is committed to the repo (unlike the private key) so that every
firmware build ships with the fleet's trusted DFU public key compiled in.

Format produced:
    FW_SIGNING_PUBKEY[65]   — uncompressed SEC1 point  (0x04 || X[32] || Y[32])
    FW_SIGNING_PUBKEY_FP[32] — SHA-256 of the SubjectPublicKeyInfo DER, used as
                                the "which key is this" fingerprint in INFO.

Re-run this tool after every keygen.py invocation.  The firmware must be
rebuilt and re-flashed to every device in the fleet for the new public key
to take effect.

Requires:  pip install cryptography
"""
import hashlib
import pathlib
import sys

try:
    from cryptography.hazmat.primitives import serialization
except ImportError:
    sys.exit("cryptography package not found — run: pip install cryptography")


REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
PUB_PATH  = REPO_ROOT / "keys" / "signing_public.pem"
OUT_PATH  = REPO_ROOT / "main" / "signing_pubkey.h"


HEADER = """\
/**
 * signing_pubkey.h — AUTO-GENERATED by tools/embed_pubkey.py.
 *
 * ECDSA P-256 public key that the firmware trusts for DFU image signatures.
 * The matching private key lives in keys/signing_private.pem (gitignored).
 *
 * Regenerate by running:   python tools/embed_pubkey.py
 *
 * Replacing this file invalidates every device still running a firmware that
 * was built with the previous key — plan rollouts accordingly.
 */
#pragma once

#include <stdint.h>

"""


def format_bytes(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> int:
    if not PUB_PATH.exists():
        print(f"Missing {PUB_PATH} — run tools/keygen.py first.")
        return 1

    pub = serialization.load_pem_public_key(PUB_PATH.read_bytes())
    sec1 = pub.public_bytes(
        encoding=serialization.Encoding.X962,
        format=serialization.PublicFormat.UncompressedPoint,
    )
    if len(sec1) != 65 or sec1[0] != 0x04:
        print(f"Unexpected public-key encoding: {len(sec1)} bytes, "
              f"first byte 0x{sec1[0]:02x}")
        return 1

    spki = pub.public_bytes(
        encoding=serialization.Encoding.DER,
        format=serialization.PublicFormat.SubjectPublicKeyInfo,
    )
    fp = hashlib.sha256(spki).digest()

    OUT_PATH.write_text(
        HEADER
        + format_bytes("FW_SIGNING_PUBKEY", sec1) + "\n\n"
        + format_bytes("FW_SIGNING_PUBKEY_FP", fp) + "\n"
    )

    print(f"Wrote {OUT_PATH}")
    print(f"   pubkey fingerprint: {fp.hex()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
